// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Booking.Services.App.Models.Models;

public partial class Experience
{
    public string Id { get; set; }

    public string UserId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public bool? Approved { get; set; }

    public DateTime? CreatedAt { get; set; }
}