// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Booking.Services.App.Models.Models;

public partial class Faq
{
    public string Id { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public bool? Approved { get; set; }
}