// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Booking.Services.App.Models.Models;

public partial class Gallery
{
    public string Id { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public DateTime? UploadedAt { get; set; }
}