// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Booking.Services.App.Models.Models;

public partial class Payment
{
    public string Id { get; set; }

    public string ReservationId { get; set; }

    public string StripePaymentId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Reservation Reservation { get; set; }
}