// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Booking.Services.App.Models.Models;

public partial class ReservationService
{
    public string Id { get; set; }

    public string ReservationId { get; set; }

    public string ServiceId { get; set; }

    public int? Quantity { get; set; }

    public decimal SubTotal { get; set; }

    public virtual Reservation Reservation { get; set; }

    public virtual Service Service { get; set; }
}