// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Booking.Services.App.Models.Models;

public partial class ServiceCategory
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Icon { get; set; }

    public int? Order { get; set; }

    public sbyte? IsActive { get; set; }

    public sbyte? Deleted { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
}