// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Booking.Services.App.Models.Models;

public partial class Service
{
    public string Id { get; set; }

    public string CategoryId { get; set; }

    public string Title { get; set; }

    public string Subtitle { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public sbyte? IsActive { get; set; }

    public sbyte? IsOptional { get; set; }

    public sbyte? IsFeatured { get; set; }

    public decimal? PricePerDay { get; set; }

    public DateTime? CreatedAt { get; set; }

    public sbyte? Deleted { get; set; }

    public virtual ServiceCategory Category { get; set; }
}